# Generated by Django 5.1.5 on 2025-01-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AddField(
            model_name='variable',
            name='external_reference',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
