# Generated by Django 5.1.5 on 2025-01-21 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0003_alter_variable_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.RemoveField(
            model_name='variable',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='variablevalue',
            name='date',
        ),
        migrations.AddField(
            model_name='variablevalue',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='visualizer.unit'),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
