# Generated by Django 5.1.5 on 2025-01-21 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0004_unit_remove_variable_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='visualizer.unit'),
        ),
        migrations.AlterField(
            model_name='variablevalue',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
