# Generated by Django 5.1.5 on 2025-01-21 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0005_alter_variable_unit_alter_variablevalue_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='visualizer.unit'),
        ),
    ]
