# Generated by Django 5.1.5 on 2025-01-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0007_alter_variable_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
